name: Publish

on:
  issue_comment:
    types: [created, edited]

jobs:
  publish:
    name: Setup Package
    if: ${{ !github.event.issue.pull_request }} && constrains(github.event.comment.body, 'Release \#')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup env
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: yarn install
      - name: Publish
        run: yarn publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Auto Move
        uses: hungluu/move-tasks@v2
        with:
          actionToken: ${{secrets.GIT_TOKEN}}
          repository: quocthoaitran/hello-teku
          project: quocthoaitran/hello-teku/projects/1
          fromCards: >
            $project
              > columns(name is Merged)
              > cards(contentId is ${{ github.event.issue.id }})
          toColumn: $project > columns(name is Released)
    
