name: Publish

on:
  issue_comment:
    types: [created, edited]

jobs:
  publish:
    name: Setup Package
    if: >
      !github.event.issue.pull_request
      && contains(github.event.comment.body, 'Release')
      && contains(join(github.event.issue.labels.*.name, ', '), 'package:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - name: Create comment on issue
        token: ${{secrets.GIT_TOKEN}}
        repository: quocthoaitran/hello-teku
        with:
          issue-number: {{ github.event.issue.number }}
          body: `Publishing ${{ package-version.outputs.name}}:${{ package-version.outputs.version }}`
      - name: Setup env
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: yarn install
      - name: Publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Auto Move
        uses: hungluu/move-tasks@v2
        with:
          actionToken: ${{secrets.GIT_TOKEN}}
          repository: quocthoaitran/hello-teku
          project: quocthoaitran/hello-teku/projects/1
          fromCards: >
            $project
              > columns(name is Merged)
              > cards(contentId is ${{ github.event.issue.id }})
          toColumn: $project > columns(name is Released)
    
